### ISSUE TITLE
Security.Test Bmc Expire Password.Expire And Change Root Password Via GUI  - failure to find USERNAME field

### ISSUE THREAD

**Issue by generatz** [openbmc/openbmc-test-automation#2146]
The test grabs a screenshot of the login page, but then cannot find the login field:
```
16:36:39.766 	FAIL 	Element with locator '//*[@data-test-id='login-input-username']' not found. 	
16:36:39.766 	DEBUG 	Traceback (most recent call last):
  File "/home/jenkins/workspace/security/temp-python/lib/python3.6/site-packages/SeleniumLibrary/__init__.py", line 492, in run_keyword
    return DynamicCore.run_keyword(self, name, args, kwargs)
  File "/home/jenkins/workspace/security/temp-python/lib/python3.6/site-packages/robotlibcore.py", line 94, in run_keyword
    return self.keywords[name](*args, **(kwargs or {}))
  File "/home/jenkins/workspace/security/temp-python/lib/python3.6/site-packages/SeleniumLibrary/keywords/waiting.py", line 369, in wait_until_element_is_enabled
    error,
  File "/home/jenkins/workspace/security/temp-python/lib/python3.6/site-packages/SeleniumLibrary/keywords/waiting.py", line 426, in _wait_until
    self._wait_until_worker(condition, timeout, error)
  File "/home/jenkins/workspace/security/temp-python/lib/python3.6/site-packages/SeleniumLibrary/keywords/waiting.py", line 443, in _wait_until_worker
    raise AssertionError(not_found or error)
```

I have examined the screen shot and it looks fine AFAIK, so I'm guessing that the test is not working because the login page is not as expected. The screen shot is attached.
![selenium-screenshot-1](https://user-images.githubusercontent.com/6298273/148862443-aeac6e5c-46c7-4daa-ad52-f2a157e851f6.png)

**Comment by generatz** [comment]
In case this helps as a point of reference: this GUI-related test _is_ working for me:
Security.Test Bmc Connections.Test Stability On Large Number Of Wrong Login Attempts To GUI

**Comment by gkeishin** [comment]
@prkatti1 can you check on this one.

**Comment by prkatti1** [comment]
Looking into it.
By the way which BMC version you are using for testing here?? @generatz

**Comment by generatz** [comment]
@prkatti1 It is a development version. It self-reports as "2.10.0-dev"...

**Comment by generatz** [comment]
Since raising this issue I learned that this BMC is using Angular JS. 
I think the test probably expects vue.js?

**Comment by gkeishin** [comment]
Thank you @generatz   Yes the new Vue has changes. This is due to XPATH , and somehow it doesn't seem to find it.  Please clone the latest and try.

16:36:39.766 	FAIL 	Element with locator '//*[@data-test-id='login-input-username']' not found. 

we have tested it and working for us. If you still see it.. let us know. Thanks.
