### ISSUE TITLE
Run cases in ipmi/test_ipmi_chassis.robot but got failed

### ISSUE THREAD

**Issue by nba2023** [openbmc/openbmc-test-automation#2241]
Run the case `IPMI Chassis Status On`, and get error as follows:
The first error:
```
[ ERROR ] Error in file '/openbmc/extended/obmc_boot_test_resource.robot' on line 9: Importing library '/openbmc/lib/obmc_boot_test.py' failed: 
#(UTC) 2024/05/22 00:49:22.155861 -    1.461193 - **ERROR** Failed to find complete path for file "/openbmc/data/boot_lists/PDU_reboot".
shell_rc:                                         0x0000000000000001

Traceback (most recent call last):
  File "/openbmc/lib/obmc_boot_test.py", line 58, in <module>
    boot_lists = read_boot_lists()
  File "/openbmc/lib/boot_data.py", line 145, in read_boot_lists
    file_path = gm.which(dir_path + boot_category)
  File "/openbmc/lib/gen_misc.py", line 137, in which
    BuiltIn().fail(gp.sprint_error(error_message))
  File "/usr/local/lib/python3.6/dist-packages/robot/libraries/BuiltIn.py", line 534, in fail
    raise AssertionError(msg) if msg else AssertionError()
PYTHONPATH:
  /usr/local/bin
  /usr/lib/python36.zip
  /usr/lib/python3.6
  /usr/lib/python3.6/lib-dynload
  /usr/local/lib/python3.6/dist-packages
  /usr/lib/python3/dist-packages
  /openbmc/data/
  /openbmc/data/
  /openbmc/
  /openbmc/data/
  /openbmc/extended/
```
The end error:
```
No keyword with name 'OBMC Boot Test Py' found. Did you mean:
    obmc_boot_test_resource.OBMC Boot Test

Also keyword teardown failed:
No keyword with name 'OBMC Boot Test Teardown' found.
| FAIL |
No keyword with name 'OBMC Boot Test Py' found. Did you mean:
    obmc_boot_test_resource.OBMC Boot Test

Also keyword teardown failed:
No keyword with name 'OBMC Boot Test Teardown' found.
```
Anyone can help me to fix it? Thanks.

**Comment by nba2023** [comment]
Attachment file is the log.html.
[log.zip](https://github.com/openbmc/openbmc-test-automation/files/15384898/log.zip)

**Comment by gkeishin** [comment]
@nba2023
1.  First is to move the Python up to 3.10 or 3.11 
2.  Next please check the file if it's missing 
```
Error in file '/openbmc/extended/obmc_boot_test_resource.robot' on line 9: Importing library '/openbmc/lib/obmc_boot_test.py' failed: #(UTC) 2024/05/21 05:24:58.969319 -    1.604266 - **ERROR** Failed to find complete path for file "/openbmc/data/boot_lists/PDU_reboot".

```
3. Run the test from the top of the directory after cloning

```
git clone https://github.com/openbmc/openbmc-test-automation
cd openbmc-test-automation/

robot -v xxxxxx run from this directory
```

**Comment by nba2023** [comment]
> @nba2023
> 
>     1. First is to move the Python up to 3.10 or 3.11
> 
>     2. Next please check the file if it's missing
> 
> 
> ```
> Error in file '/openbmc/extended/obmc_boot_test_resource.robot' on line 9: Importing library '/openbmc/lib/obmc_boot_test.py' failed: #(UTC) 2024/05/21 05:24:58.969319 -    1.604266 - **ERROR** Failed to find complete path for file "/openbmc/data/boot_lists/PDU_reboot".
> ```
> 
>     3. Run the test from the top of the directory after cloning
> 
> 
> ```
> git clone https://github.com/openbmc/openbmc-test-automation
> cd openbmc-test-automation/
> 
> robot -v xxxxxx run from this directory
> ```

Hi, 
The case can run after upgrade python to 3.11.9 without end error.
But still got same error as follows:
```
[ ERROR ] Error in file '/openbmc/extended/obmc_boot_test_resource.robot' on line 9: Importing library '/openbmc/lib/obmc_boot_test.py' failed: #(UTC) 2024/06/05 07:03:57.564355 -    0.191447 - **ERROR** Failed to find complete path for file "/openbmc/data/boot_lists/PDU_reboot".
shell_rc:                                         0x0000000000000001

Traceback (most recent call last):
  File "/openbmc/lib/obmc_boot_test.py", line 56, in <module>
    boot_lists = read_boot_lists()
                 ^^^^^^^^^^^^^^^^^
  File "/openbmc/lib/boot_data.py", line 145, in read_boot_lists
    file_path = gm.which(dir_path + boot_category)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/openbmc/lib/gen_misc.py", line 128, in which
    BuiltIn().fail(gp.sprint_error(error_message))
  File "/usr/local/lib/python3.11/site-packages/robot/libraries/BuiltIn.py", line 529, in fail
    raise AssertionError(msg) if msg is not None else AssertionError()
PYTHONPATH:
  /openbmc/lib
  /usr/local/bin
  /usr/local/lib/python311.zip
  /usr/local/lib/python3.11
  /usr/local/lib/python3.11/lib-dynload
  /usr/local/lib/python3.11/site-packages
  /openbmc/data/
  /openbmc/data/
  /openbmc/data/
  /openbmc/extended/
  /openbmc/data/
  /openbmc/extended/
Openbmc.Ipmi.Test Ipmi Chassis :: Module to test IPMI chassis functionality.
```

I enter to docker container and check the missing file under /openbmc
root@vm:/home/user# docker exec -it 008 bash
```
root@vm:/openbmc# cat /openbmc/data/boot_lists/PDU_reboot
APOR
APOR (mfg)
PDU AC Cycle (run)
PDU AC Cycle (run) (mfg)
PDU AC Cycle (off)
PDU AC Cycle (off) (mfg)
```

**Comment by v9035** [comment]
i see this issue in python 3.10. The python file is imported to ***/extended/obmc_boot_test_resource.robot and last line in the file for keyword definition is where the same error occurs 
    Obmc Boot Test Py  &{arguments}

**Comment by gkeishin** [comment]
I ran on older and newer Python and robot version
```
Robot Framework 7.2.2 (Python 3.10.12 on linux
Robot Framework 7.2.2 (Python 3.12.9 on linux)
```

and it works for me. 

I assume you are able to run this and works clean ?

robot -v OPENBMC_HOST:xx.xx.xx.xx templates/test_openbmc_setup.robot

```
..

Front Panel Control  : none
Test IPMI Setup :: Verify Out-of-band works.                          | PASS |
------------------------------------------------------------------------------
Test Openbmc Setup :: Test suite to verify if the Robot setup is r... | PASS |
3 tests, 3 passed, 0 failed
==============================================================================
```

**Comment by v9035** [comment]
after changing files permission under /openbmc/data/boot_lists/PDU_reboot the error was fixed. The code tries to get the boot commands but not sure why robot should throw error.
I thought the file was not included properly and was debugging but somehow permission fixed it.

**Comment by gkeishin** [comment]
Thanks @v9035  Closing the ticket.
