### ISSUE TITLE
[Automation] obmc_boot_test.robot Test case failure

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#230]
`Error in file '/tmp/root/15216/obmc-robot/tests/obmc_boot_test.robot': Importing test library '/tmp/root/15216/obmc-robot/lib/boot/powerons.py' failed: Resource file 'utils.robot' does not exist.`
Traceback (most recent call last):
  File "/tmp/root/15216/obmc-robot/lib/boot/powerons.py", line 14, in <module>
    BuiltIn().import_resource("utils.robot")
  File "/tmp/root/15216/obmc-robot/.tox/witherspoon/local/lib/python2.7/site-packages/robot/libraries/BuiltIn.py", line 2555, in import_resource
    raise RuntimeError(unic(err))
PYTHONPATH:
  /tmp/root/15216/obmc-robot/.tox/witherspoon/lib/python2.7
  /tmp/root/15216/obmc-robot/.tox/witherspoon/lib/python2.7/plat-powerpc64le-linux-gnu
  /tmp/root/15216/obmc-robot/.tox/witherspoon/lib/python2.7/lib-tk
  /tmp/root/15216/obmc-robot/.tox/witherspoon/lib/python2.7/lib-old
  /tmp/root/15216/obmc-robot/.tox/witherspoon/lib/python2.7/lib-dynload
  /usr/lib/python2.7
  /usr/lib/python2.7/plat-powerpc64le-linux-gnu
  /usr/lib/python2.7/lib-tk
  /tmp/root/15216/obmc-robot/.tox/witherspoon/local/lib/python2.7/site-packages
  /tmp/root/15216/obmc-robot/.tox/witherspoon/lib/python2.7/site-packages

**Comment by gkeishin** [comment]
@micwalsh Can you take a look at this... and this test is now planned to moved to extended because this requires PDU and Host related info before executing. 

There are two buckets available in OpenBMC for test
1. Under tests  - Specific to BMC stack testing
2. Under extended - BMC + Host + others

**Comment by gkeishin** [comment]
I have pushed the code to move to extended https://gerrit.openbmc-project.xyz/#/c/1364/

Now remaining is this error as mentioned in the defect..
