### ISSUE TITLE
Unable to flash the pnor correctly

### ISSUE THREAD

**Issue by pragupta** [openbmc/openbmc-test-automation#524]
I have seen this a few times where we are not able to flash the pnor:
"Keyword 'Is PNOR Flash Done' failed after retrying for 7 minutes. The last error was: Flash Error != Flash Done"

But, when I manually flash the system, it works. Here is the jenkins link with the failure:
http://gfw160.aus.stglabs.ibm.com:8088/jenkins/job/OP_HW_test_multi_p9/268/MACHINE=witherspoon/artifact/openbmc-test-automation/log.html

**Comment by pragupta** [comment]
Had a few more jenkins run fail due to scp timeout... A/C cycling the machine seems to fix the problem.

12:00:52.784	TRACE	Arguments: [ '/tmp/hostboot/jenkins-slave/workspace/OP_HW_test_multi_p9/MACHINE/witherspoon/test_images/witherspoon/witherspoon.pnor' | '/tmp' ]	
12:00:52.784	DEBUG	[chan 0] Max packet in: 32768 bytes	
12:00:57.900	FAIL	timeout	
12:00:57.900	DEBUG	Traceback (most recent call last):
  File "/gsa/ausgsa/projects/h/hostboot/optools/python2.7_VE/lib/python2.7/site-packages/SCPLibrary/library.py", line 97, in put_file
    self.scp_client.put(local_filepath, remote_filepath, recursive=False)
  File "/gsa/ausgsa/projects/h/hostboot/optools/python2.7_VE/lib/python2.7/site-packages/scp.py", line 154, in put
    self._send_files(files)
  File "/gsa/ausgsa/projects/h/hostboot/optools/python2.7_VE/lib/python2.7/site-packages/scp.py", line 249, in _send_files
    chan.sendall(file_hdl.read(buff_size))
  File "/gsa/ausgsa/projects/h/hostboot/optools/python2.7_VE/lib/python2.7/site-packages/paramiko/channel.py", line 761, in sendall
    sent = self.send(s)
  File "/gsa/ausgsa/projects/h/hostboot/optools/python2.7_VE/lib/python2.7/site-packages/paramiko/channel.py", line 715, in send
    return self._send(s, m)
  File "/gsa/ausgsa/projects/h/hostboot/optools/python2.7_VE/lib/python2.7/site-packages/paramiko/channel.py", line 1082, in _send
    size = self._wait_for_send_window(size)
  File "/gsa/ausgsa/projects/h/hostboot/optools/python2.7_VE/lib/python2.7/site-packages/paramiko/channel.py", line 1201, in _wait_for_send_window
    raise socket.timeout()
