### ISSUE TITLE
[Documentation]  Update README for tox version info

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#73]
Documentation README , reads like this
Install the python dependencies for tox

    $ easy_install tox==2.1.1
    $ easy_install pip

This version doesn't work for newer syntax of the tox. Need to upgrade to at least 2.3.1 or latest...

**Comment by jazurin** [comment]
For reference, I'm pasting the error I was seeing while running with tox version 2.1.1.  Upgrading to 2.3.1 resolved the problem.

`(python2.7_VE)gfw172$  tox -e palmetto -- tests/test_sensors.robot
Traceback (most recent call last):
 File "/gsa/ausgsa/projects/h/hostboot/optools/python2.7_VE/bin/tox", line 9, in <module>
   load_entry_point('tox==2.1.1', 'console_scripts', 'tox')()
 File "/gsa/ausgsa/projects/h/hostboot/optools/python2.7_VE/lib/python2.7/site-packages/tox-2.1.1-py2.7.egg/tox/session.py", line 38, in main
   config = prepare(args)
 File "/gsa/ausgsa/projects/h/hostboot/optools/python2.7_VE/lib/python2.7/site-packages/tox-2.1.1-py2.7.egg/tox/session.py", line 26, in prepare
   config = parseconfig(args)
 File "/gsa/ausgsa/projects/h/hostboot/optools/python2.7_VE/lib/python2.7/site-packages/tox-2.1.1-py2.7.egg/tox/config.py", line 219, in parseconfig
   parseini(config, inipath)
 File "/gsa/ausgsa/projects/h/hostboot/optools/python2.7_VE/lib/python2.7/site-packages/tox-2.1.1-py2.7.egg/tox/config.py", line 669, in __init__
   self.make_envconfig(name, section, reader._subs, config)
 File "/gsa/ausgsa/projects/h/hostboot/optools/python2.7_VE/lib/python2.7/site-packages/tox-2.1.1-py2.7.egg/tox/config.py", line 697, in make_envconfig
   res = meth(env_attr.name, env_attr.default)
 File "/gsa/ausgsa/projects/h/hostboot/optools/python2.7_VE/lib/python2.7/site-packages/tox-2.1.1-py2.7.egg/tox/config.py", line 864, in getargvlist
   return _ArgvlistReader.getargvlist(self, s)
 File "/gsa/ausgsa/projects/h/hostboot/optools/python2.7_VE/lib/python2.7/site-packages/tox-2.1.1-py2.7.egg/tox/config.py", line 1016, in getargvlist
   commands.append(cls.processcommand(reader, current_command))
 File "/gsa/ausgsa/projects/h/hostboot/optools/python2.7_VE/lib/python2.7/site-packages/tox-2.1.1-py2.7.egg/tox/config.py", line 1046, in processcommand
   new_word = reader._replace(word)
 File "/gsa/ausgsa/projects/h/hostboot/optools/python2.7_VE/lib/python2.7/site-packages/tox-2.1.1-py2.7.egg/tox/config.py", line 982, in _replace
   return RE_ITEM_REF.sub(self._replace_match, x)
 File "/gsa/ausgsa/projects/h/hostboot/optools/python2.7_VE/lib/python2.7/site-packages/tox-2.1.1-py2.7.egg/tox/config.py", line 978, in _replace_match
   return handler(match)
 File "/gsa/ausgsa/projects/h/hostboot/optools/python2.7_VE/lib/python2.7/site-packages/tox-2.1.1-py2.7.egg/tox/config.py", line 922, in _replace_env
   (envkey, envkey))
tox.ConfigError: ConfigError: substitution env:'ARG_FILE': unknown environment variable 'ARG_FILE'`
