### ISSUE TITLE
Automation is getting stuck due to too many files open

### ISSUE THREAD

**Issue by rahulmah** [openbmc/openbmc-test-automation#776]
Automation is getting stuck due to too many files open. If we try to do REST login it says "SSL connect error"

```
bash-4.1$ curl -c cjar -b cjar -k -H "Content-Type: application/json" -X POST https://<bmc_ip>/login -d "{\"data\": [ \"root\", \"0penBmc\" ] }"
curl: (35) SSL connect error
bash-4.1$

```

Snap shot from journal log.
```
Jun 29 04:43:40 witherspoon phosphor-gevent[905]: error: [Errno 24] **Too many open files**
Jun 29 04:43:40 witherspoon phosphor-gevent[905]: <WSGIServer at 0x765a58b0 fileno=5 address=('::2cc2:f848:b08d:b176%1991347616', 443, 0, 1991347616)> failed with error
Jun 29 04:43:40 witherspoon phosphor-gevent[905]: Traceback (most recent call last):
Jun 29 04:43:40 witherspoon phosphor-gevent[905]:   File "/usr/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
Jun 29 04:43:40 witherspoon phosphor-gevent[905]:     result = self._run(*self.args, **self.kwargs)
Jun 29 04:43:38 witherspoon dropbear[12913]: Exit (root): Error reading: Connection reset by peer
Jun 29 04:43:41 witherspoon phosphor-gevent[905]:   File "/usr/lib/python2.7/site-packages/gevent/server.py", line 102, in wrap_socket_and_handle
Jun 29 04:43:41 witherspoon phosphor-gevent[905]:     ssl_socket = self.wrap_socket(client_socket, **self.ssl_args)
Jun 29 04:43:41 witherspoon phosphor-gevent[905]:   File "/usr/lib/python2.7/site-packages/gevent/ssl.py", line 404, in wrap_socket
Jun 29 04:43:41 witherspoon phosphor-gevent[905]:     ciphers=ciphers)
Jun 29 04:43:41 witherspoon phosphor-gevent[905]:   File "/usr/lib/python2.7/site-packages/gevent/ssl.py", line 106, in __init__
Jun 29 04:43:41 witherspoon phosphor-gevent[905]:     cert_reqs, ssl_version, ca_certs)
Jun 29 04:43:41 witherspoon phosphor-gevent[905]:   File "/usr/lib/python2.7/site-packages/gevent/ssl.py", line 31, in new_sslwrap
Jun 29 04:43:41 witherspoon phosphor-gevent[905]:     context.load_cert_chain(certfile, keyfile)
Jun 29 04:43:41 witherspoon phosphor-gevent[905]: IOError: [Errno 24] **Too many open files**
Jun 29 04:43:41 witherspoon phosphor-gevent[905]: <Greenlet at 0x7591d1c0: <bound method WSGIServer.wrap_socket_and_handle of <WSGIServer at 0x765a58b0 fileno=5 address=('::2cc2:f848:b08d:b176%1991347616', 443, 0, 1991347616)>>(<socket at 0x759249b0 fileno=1023>, ('::6099:af76:8e91:f402%1224190740', 32964, 0, 122)> failed with IOError
Jun 29 04:43:39 witherspoon dropbear[12920]: Exit (root): Error writing: Connection reset by peer
Jun 29 04:43:39 witherspoon dropbear[12928]: Exit (root): Exited normally
Jun 29 04:43:39 witherspoon dropbear[12955]: Exit (root): Exited normally
Jun 29 04:43:39 witherspoon dropbear[12997]: Exit (root): Exited normally
```

**Comment by gkeishin** [comment]
Reference https://github.com/openbmc/openbmc/issues/1389
